#!/bin/bash

# Base image to build NPM related packages (Stage1) (big image)

FROM node:18 AS builder

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

# Base image to run application only (Stage2) (small image)

FROM node:18-alpine

WORKDIR /app

COPY --from=builder /app .

EXPOSE 5173

CMD ["npm","run","dev"]




