version: "3.8"

services:
  online_shop:
    build:
      context: .

    container_name: online_shop
    ports:
      - "5173:5173"
    networks:
      - my-net
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173/"]
      interval: 60s
      timeout: 10s
      retries: 5

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    networks:
      - my-net

networks:
  my-net:

